#!/usr/bin/env bash
# This script displays:
#  To infinity and beyond indefinitely
#  With a sleep 2 in between each iteration
#  I am invincible!!! when receiving a SIGTERM signal

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

# Set up the trap to call the function on SIGTERM
trap 'handle_sigterm' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
