#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username password userid groupid useridinfo home commandshell
do
	echo "The user $username is part of the $groupid gang, lives in $home and rides $commandshell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < "/etc/passwd"
